version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_indoor_duration
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${PORT_DB}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  indoor_duration_app:
    build: .
    container_name: fastapi_indoor_duration
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "${PORT_APP}:8000"
    environment:
      - TZ=Asia/Jakarta

volumes:
  postgres_data:
