"""update field person_duration

Revision ID: 6143b7087caf
Revises: 5c79cc00c53e
Create Date: 2025-02-08 09:57:03.053697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6143b7087caf'
down_revision: Union[str, None] = '5c79cc00c53e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person_durations', sa.Column('status', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person_durations', 'status')
    # ### end Alembic commands ###