"""add field expires in user token table

Revision ID: 96be56f1cf35
Revises: 9839a44ed849
Create Date: 2025-02-07 11:08:21.356399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '96be56f1cf35'
down_revision: Union[str, None] = '9839a44ed849'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_tokens', sa.Column('expires_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_tokens', 'expires_at')
    # ### end Alembic commands ###