"""add_init2

Revision ID: 9839a44ed849
Revises: adc384b4423c
Create Date: 2025-02-06 23:06:00.605132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session
import sqlmodel
from db.seeds import seed_all


# revision identifiers, used by Alembic.
revision: str = '9839a44ed849'
down_revision: Union[str, None] = 'adc384b4423c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Tambahkan seeder setelah migrasi
    bind = op.get_bind()
    session = Session(bind=bind)
    seed_all(session)  # Menjalankan seeder


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###