"""update table person duration and detail

Revision ID: a7e4c8865bf0
Revises: 360756665c22
Create Date: 2025-02-08 08:56:01.676372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a7e4c8865bf0'
down_revision: Union[str, None] = '360756665c22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('detail_person_durations', 'end_time',
               existing_type=sa.VARCHAR(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('detail_person_durations', 'end_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###