"""update new endtime

Revision ID: c0abaa0caf12
Revises: 6065a8a0f626
Create Date: 2025-02-08 09:06:46.876749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c0abaa0caf12'
down_revision: Union[str, None] = '6065a8a0f626'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detail_person_durations', sa.Column('total_duration', postgresql.TIMESTAMP(), nullable=False))
    op.drop_column('detail_person_durations', 'end_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detail_person_durations', sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('detail_person_durations', 'total_duration')
    # ### end Alembic commands ###