"""update field table logs

Revision ID: d8714ccd30b8
Revises: 24d606e25603
Create Date: 2025-02-09 23:55:21.793978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd8714ccd30b8'
down_revision: Union[str, None] = '24d606e25603'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('name', sa.VARCHAR(length=255), nullable=False))
    op.drop_column('logs', 'user_uid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('user_uid', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_column('logs', 'name')
    # ### end Alembic commands ###